[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
diesel = { version = "2.0.3", features = ["postgres", "r2d2", "chrono", "uuid"] }
chrono = { version = "0.4.31", features = ["serde"] }
uuid = { version = "1.4.1", features = ["v4"] }
dotenv = "0.15.0"
rand = "0.7"
rust-argon2 = "0.5"
diesel_migrations = "1.4"
log = "0.4"
env_logger = "0.6"
listenfd = "0.3"
lazy_static = "1.4"